name: Test SOCKS5 Proxies

on:
  push:  # 当有代码推送到这个仓库时触发
    branches:
      - main  # 你也可以指定其他分支
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  test_proxies:
    runs-on: ubuntu-latest

    steps:
    # 检出代码
    - name: Checkout repository
      uses: actions/checkout@v3

    # 设置 Python 环境
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x  # 指定 Python 版本
    
    # 安装依赖
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests[socks]

    # 运行 SOCKS5 代理延迟测试脚本
    - name: Run SOCKS5 proxy latency test
      env:
        PROXYIP: ${{ secrets.PROXYIP }}
      run: python test.py

    # 如果脚本失败，触发 GitHub Actions 任务失败
    - name: Check for failures
      if: failure()
      run: echo "One or more proxies failed."
